// Generates contracts/test/fixtures/account-vectors.json.
//
//   node zk/account-vectors.ts
//
// FORS signatures over UserOperation digests, made by the same TypeScript a
// wallet runs (chain/pq-account.ts for the payload and the address,
// @opaque/pq-wallet for the digest and the signature), then checked by
// contracts/test/PQAccount.t.sol. Addresses are fixed constants, placed with
// deployCodeTo, because the digest binds the account address and the account
// address binds the factory and the implementation.

import { writeFileSync } from 'node:fs';

import { asAddress, asChainId, fromHex, toHex } from '@opaque/protocol-types/codecs.js';
import type { Bytes32, Hex } from '@opaque/protocol-types';
import { encodeSignature, forsSchemeId, FORS_C_DEFAULT, keyGen, pkCommitment, pqDigest, sign, utf8 } from '@opaque/pq-wallet';
import { keccak_256 } from '@noble/hashes/sha3.js';

import { accountSalt, predictAccount, userOperationPayload } from '../chain/pq-account.ts';

const CHAIN_ID = 31337n;
const REGISTRY = asAddress('0x0000000000000000000000000000000000002222');
const VALIDATOR = asAddress('0x0000000000000000000000000000000000006666');
const ENTRY_POINT = asAddress('0x0000000000000000000000000000000000007777');
const IMPLEMENTATION = asAddress('0x0000000000000000000000000000000000008888');
const FACTORY = asAddress('0x0000000000000000000000000000000000009999');
const USER_ACTION_DOMAIN = 'opaque/v1/pq-wallet/action';
const MAX_USES = 4n;
const DEADLINE = 1_000_000n;

// Fixed seeds: a fixture must reproduce. NEVER keys for anything real.
const keyA = keyGen(new Uint8Array(32).fill(0xa1), FORS_C_DEFAULT);
const keyB = keyGen(new Uint8Array(32).fill(0xb2), FORS_C_DEFAULT);
const pkA = pkCommitment(keyA.publicKey) as Bytes32;
const pkB = pkCommitment(keyB.publicKey) as Bytes32;

const salt = accountSalt(pkA, pkB, MAX_USES, DEADLINE);
const account = predictAccount(FACTORY, IMPLEMENTATION, salt);

const opHash = (n: number): Bytes32 => toHex(keccak_256(utf8(`opaque/test/user-operation/${n}`))) as Bytes32;

function signOp(key: typeof keyA, userOpHash: Bytes32, useCount: bigint): Hex {
  const payload = toHex(new Uint8Array([...utf8(USER_ACTION_DOMAIN), ...fromHex(userOperationPayload(userOpHash))])) as Hex;
  const digest = pqDigest({ chainId: asChainId(CHAIN_ID), walletAddress: account, schemeId: forsSchemeId(key.publicKey.params), useCount, payload });
  return encodeSignature(key.publicKey, sign(key.secretKey, digest));
}

const out = {
  $comment: 'Generated by backend/zk/account-vectors.ts. Test keys from fixed seeds — never real.',
  chainId: Number(CHAIN_ID),
  registry: REGISTRY, validator: VALIDATOR, entryPoint: ENTRY_POINT, implementation: IMPLEMENTATION, factory: FACTORY,
  pkA, pkB, maxUses: Number(MAX_USES), deadline: Number(DEADLINE),
  salt, account,
  userOpHash0: opHash(0), userOpHash1: opHash(1),
  userOperationPayload0: userOperationPayload(opHash(0)),
  sigOp0: signOp(keyA, opHash(0), 0n),
  sigOp1: signOp(keyA, opHash(1), 1n),
  sigWrongKey0: signOp(keyB, opHash(0), 0n),
};

const path = new URL('../../contracts/test/fixtures/account-vectors.json', import.meta.url);
writeFileSync(path, `${JSON.stringify(out, null, 2)}\n`);
process.stdout.write(`wrote ${path.pathname}\n  account ${account}\n`);
