#!/usr/bin/env node
// Builds a real sealed intent for the simulator, and puts the two secrets it
// needs into .env.
//
// This runs under NODE, not Javy: it needs an RNG, and generating keys is a
// client/offline job. That is exactly the split sealed-intent.ts is built
// around — seal-client.ts here, sealed-intent.ts inside the enclave.
//
// EVERYTHING THIS PRODUCES IS SIMULATION-ONLY. The ML-KEM keypair and the
// credential MAC key are generated fresh on every run and written to .env,
// which is gitignored. A real deployment generates the keypair on an offline
// machine and puts the secret half in the Vault DON with `cre secrets create`.
//
// Secret values are written straight to the file and never printed: the two
// SECRET_ lines below are the only place they exist.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { Address, Bytes32, Hex, PrivateSpend, UnixSeconds } from '@opaque/protocol-types';
import { spendHash } from '@opaque/protocol-types/codecs.js';

import { issueCredential } from '../../backend/cre/credential.ts';
import { generateIntentKeypair, sealIntent } from '../../backend/cre/seal-client.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const KEY_ID = 'opaque-intent-key-v1';
const POLICY_VERSION = 'opaque-policy-v1';
const recipient = `0x${'a11ce0'.padEnd(40, '0')}` as Address;

// A spend the pool would accept. The proof is a placeholder: this fixture is
// about the confidential path, and the pool verifies proofs independently.
const spend: PrivateSpend = {
  mode: 'SINGLE_NOTE_PQ',
  scope: {
    chainId: 5042002n as never, // Arc
    pool: `0x${'11'.repeat(20)}` as Address,
    denomination: 1_000_000 as never, // 1 USDC, six decimals
  },
  recipient,
  nullifier: `0x${'22'.repeat(32)}` as never,
  paymentContext: `0x${'33'.repeat(32)}` as Bytes32,
  verifierId: `0x${'44'.repeat(32)}` as Bytes32,
  proof: '0xdeadbeef' as Hex,
  commitment: `0x${'55'.repeat(32)}` as never,
};

const keys = generateIntentKeypair();
const credentialSecret = `sim-credential-mac-${Date.now()}`;

// Issued by the policy authority ONCE, out of band. The enclave verifies it
// locally, so the authority never learns which payment used it.
const credential = issueCredential(
  {
    recipient,
    policyVersion: POLICY_VERSION,
    expiresAt: (BigInt(Math.floor(Date.now() / 1000)) + 86_400n) as UnixSeconds,
  },
  new TextEncoder().encode(credentialSecret),
);

// Bigints cross as decimal strings — JSON.stringify throws on them outright.
const wire = (value: unknown): string =>
  JSON.stringify(value, (_k, v) => (typeof v === 'bigint' ? v.toString(10) : v));

const sealed = sealIntent(
  keys.publicKey,
  KEY_ID,
  new TextEncoder().encode(wire({ spend, credential: wire(credential) })),
);

// ── .env: the two secrets, written, never printed ─────────────────────────
const envPath = join(root, '.env');
const env = readFileSync(envPath, 'utf8')
  .split('\n')
  .filter((line) => !/^SECRET_(INTENT_KEY|CREDENTIAL_MAC)=/.test(line))
  .join('\n')
  .replace(/\n+$/, '');
writeFileSync(
  envPath,
  `${env}\n\n# Simulation-only. Regenerated by tools/make-fixture.ts on every run.\n` +
    `SECRET_INTENT_KEY=${keys.secretKey}\nSECRET_CREDENTIAL_MAC=${credentialSecret}\n`,
  { mode: 0o600 },
);

// ── config: the public half and the ciphertext ────────────────────────────
const configPath = join(root, 'confidential-intent', 'config.staging.json');
const config = JSON.parse(readFileSync(configPath, 'utf8')) as Record<string, unknown>;
writeFileSync(
  configPath,
  `${JSON.stringify(
    {
      ...config,
      encryptionKeyId: KEY_ID,
      policyVersion: POLICY_VERSION,
      // The intent the enclave will open. Ciphertext, so it is safe in a file
      // that is committed and safe in a config the DON can read.
      sealedIntent: sealed,
      // Already past, so evaluateIntent takes the deadline branch and makes no
      // score request at all — the property that a Graph outage must never
      // strand a payment whose deadline has passed.
      deadline: (BigInt(Math.floor(Date.now() / 1000)) - 60n).toString(),
      expectedSpendHash: spendHash(spend),
      releaseTtlSeconds: '900',
      // evaluateIntent re-checks the decrypted spend against these, so a
      // payload swapped after submission is caught before any policy runs.
      chainId: spend.scope.chainId.toString(),
      pool: spend.scope.pool,
      denomination: spend.scope.denomination,
    },
    null,
    2,
  )}\n`,
);

process.stdout.write(
  `fixture written\n` +
    `  intent public key : ${keys.publicKey.slice(0, 26)}… (${keys.publicKey.length - 2} hex chars)\n` +
    `  sealed intent     : ${sealed.length - 2} hex chars\n` +
    `  recipient         : ${recipient} (inside the ciphertext only)\n` +
    `  spendHash         : ${spendHash(spend)}\n` +
    `  secrets           : written to .env, not printed\n`,
);
