// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @title Canonical length-prefixed hashing, shared with the TypeScript side.
/// @notice Every field is preceded by its 4-byte big-endian length, so no two
///         distinct field lists can produce the same byte string.
///
///         The alternative — joining with a separator — is not a style choice
///         but a forgery: with `"a:b" + "c"` and `"a" + "b:c"` hashing to the
///         same bytes, an attacker picks whichever split suits them. A
///         separator that can occur inside a field is not a separator.
///
///         These bytes are consensus with `packages/pq-wallet/src/digest.ts`
///         and `src/fors.ts`. Changing anything here is a protocol break that
///         needs new test vectors, not an edit. test/ForsVerifier.t.sol pins
///         the agreement against vectors generated by the TypeScript.
library Canonical {
    /// @dev A single field, length-prefixed.
    function field(bytes memory value) internal pure returns (bytes memory) {
        return abi.encodePacked(uint32(value.length), value);
    }

    function field(bytes32 value) internal pure returns (bytes memory) {
        return abi.encodePacked(uint32(32), value);
    }

    /// @dev `u32(x)` on the TypeScript side is a 4-byte field, so it carries a
    ///      length prefix of 4 like any other field.
    function u32Field(uint32 value) internal pure returns (bytes memory) {
        return abi.encodePacked(uint32(4), value);
    }

    /// @dev Decimal ASCII, matching `encodeBigint` in protocol-types/codecs.ts.
    ///      chainId and useCount travel as canonical decimal strings, never as
    ///      packed integers — JSON numbers lose precision above 2^53, so the
    ///      wire format settled on strings and the digest follows it.
    function decimal(uint256 value) internal pure returns (bytes memory) {
        if (value == 0) return "0";
        uint256 length;
        for (uint256 v = value; v != 0; v /= 10) length++;
        bytes memory out = new bytes(length);
        for (uint256 i = length; i > 0; i--) {
            out[i - 1] = bytes1(uint8(48 + (value % 10)));
            value /= 10;
        }
        return out;
    }
}
