export const paymentState = Object.freeze({
  WALLET_READY: 'WALLET_READY', NOTE_SELECTED: 'NOTE_SELECTED', GRAPH_SELECTING: 'GRAPH_SELECTING',
  RING_FORMED: 'RING_FORMED', ENCRYPTING_INTENT: 'ENCRYPTING_INTENT', WAITING_FOR_PRIVACY: 'WAITING_FOR_PRIVACY',
  POLICY_CHECKING: 'POLICY_CHECKING', MESH_QUEUED: 'MESH_QUEUED', SETTLED: 'SETTLED', FAILED: 'FAILED',
});
