// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {ForsVerifier} from "../src/opaque/wallet/ForsVerifier.sol";
import {Canonical} from "../src/opaque/lib/Canonical.sol";

/// The Solidity verifier and the TypeScript signer must agree on every byte of
/// every hash preimage. Reading two implementations side by side does not
/// establish that; these vectors, generated by packages/pq-wallet, do.
contract ForsVerifierTest is Test {
    struct Vectors {
        uint256 k;
        uint256 a;
        bytes32 digest;
        bytes32 pkValue;
        bytes32 pkCommitment;
        bytes signature;
        string schemeId;
    }

    Vectors internal v;

    function setUp() public {
        string memory json = vm.readFile("test/fixtures/fors-vectors.json");
        v.k = vm.parseJsonUint(json, ".k");
        v.a = vm.parseJsonUint(json, ".a");
        v.digest = vm.parseJsonBytes32(json, ".digest");
        v.pkValue = vm.parseJsonBytes32(json, ".pkValue");
        v.pkCommitment = vm.parseJsonBytes32(json, ".pkCommitment");
        v.signature = vm.parseJsonBytes(json, ".signature");
        v.schemeId = vm.parseJsonString(json, ".schemeId");
    }

    function _params() internal view returns (ForsVerifier.Params memory p) {
        p.k = uint16(v.k);
        p.a = uint8(v.a);
    }

    function test_parsesTheWireFormat() public view {
        ForsVerifier.Params memory p = this.exposedParse(v.signature);
        assertEq(p.k, uint16(v.k), "k");
        assertEq(p.a, uint8(v.a), "a");
        assertEq(v.signature.length, 3 + 32 + v.k * 32 * (1 + v.a), "encoded length");
    }

    function test_schemeIdMatchesTheTypescript() public view {
        assertEq(ForsVerifier.schemeId(_params()), v.schemeId);
    }

    function test_pkCommitmentMatchesTheTypescript() public view {
        assertEq(ForsVerifier.pkCommitment(_params(), v.pkValue), v.pkCommitment);
    }

    function test_leafIndicesMatchTheTypescript() public view {
        string memory json = vm.readFile("test/fixtures/fors-vectors.json");
        uint256[] memory expected = vm.parseJsonUintArray(json, ".indices");
        for (uint32 i = 0; i < uint32(v.k); i++) {
            assertEq(
                uint256(ForsVerifier.deriveIndex(_params(), v.digest, i)), expected[i], "index"
            );
        }
    }

    /// The whole point: a signature produced entirely off-chain by the
    /// TypeScript wallet verifies here, with no shared code.
    function test_verifiesARealSignature() public view {
        (bytes32 commitment,) = this.exposedRecover(v.signature, v.digest);
        assertEq(commitment, v.pkCommitment, "recovered commitment");
    }

    function test_rejectsATamperedDigest() public view {
        (bytes32 commitment,) = this.exposedRecover(v.signature, bytes32(uint256(v.digest) ^ 1));
        assertTrue(commitment != v.pkCommitment, "a different digest must not recover the key");
    }

    function test_rejectsATamperedLeaf() public view {
        bytes memory sig = v.signature;
        sig[35] = bytes1(uint8(sig[35]) ^ 0x01); // first leaf secret
        (bytes32 commitment,) = this.exposedRecover(sig, v.digest);
        assertTrue(commitment != v.pkCommitment, "a tampered leaf must not recover the key");
    }

    function test_rejectsATamperedAuthenticationPath() public view {
        bytes memory sig = v.signature;
        sig[67] = bytes1(uint8(sig[67]) ^ 0x01); // first path node
        (bytes32 commitment,) = this.exposedRecover(sig, v.digest);
        assertTrue(commitment != v.pkCommitment, "a tampered path must not recover the key");
    }

    /// A claimed public key that the revealed leaves do not reproduce must fail,
    /// or anyone could present any key with any leaves.
    function test_rejectsASubstitutedPublicKey() public view {
        bytes memory sig = v.signature;
        sig[3] = bytes1(uint8(sig[3]) ^ 0x01);
        (bytes32 commitment,) = this.exposedRecover(sig, v.digest);
        assertTrue(commitment != v.pkCommitment, "a substituted key must not verify");
    }

    function test_rejectsATruncatedSignature() public {
        bytes memory sig = new bytes(v.signature.length - 1);
        for (uint256 i = 0; i < sig.length; i++) sig[i] = v.signature[i];
        vm.expectRevert(ForsVerifier.MalformedSignature.selector);
        this.exposedRecover(sig, v.digest);
    }

    function test_rejectsOutOfRangeParameters() public {
        bytes memory sig = new bytes(3);
        sig[0] = 0x00;
        sig[1] = 0x00; // k = 0
        sig[2] = 0x08;
        vm.expectRevert(ForsVerifier.UnsupportedParameters.selector);
        this.exposedParse(sig);
    }

    function test_decimalEncoding() public pure {
        assertEq(string(Canonical.decimal(0)), "0");
        assertEq(string(Canonical.decimal(5042002)), "5042002");
        assertEq(string(Canonical.decimal(type(uint64).max)), "18446744073709551615");
    }

    function test_gasOfVerification() public view {
        uint256 before = gasleft();
        this.exposedRecover(v.signature, v.digest);
        // Reported, not asserted: §5.5 says measure rather than hand-wave.
        console2.log("FORS+C verify gas (k=32, a=8):", before - gasleft());
    }

    // calldata entry points, so the library sees `bytes calldata`.
    function exposedRecover(bytes calldata sig, bytes32 digest)
        external
        pure
        returns (bytes32, ForsVerifier.Params memory)
    {
        return ForsVerifier.recoverCommitment(sig, digest);
    }

    function exposedParse(bytes calldata sig) external pure returns (ForsVerifier.Params memory) {
        return ForsVerifier.parseParams(sig);
    }
}

import {console2} from "forge-std/console2.sol";
