#!/usr/bin/env node
// Generates the config three containers share: a signed directory whose
// endpoints are SERVICE NAMES, the pinned trust root, and one key per relay.
//
// Endpoints matter here. Loopback works when three relays share a host and
// fails the moment they do not, and it fails at the first forward rather than
// at startup — which is a much worse place to discover it.
//
// Everything written here is development material. The keys are freshly
// generated from the OS rather than derived, so they are real keys, but they
// land in a directory beside a compose file and should never be pointed at by
// anything a real wallet can reach.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildLocalMesh, writeLocalMesh } from '../local-mesh.ts';

const out = join(dirname(fileURLToPath(import.meta.url)), 'config');
mkdirSync(out, { recursive: true });

const mesh = buildLocalMesh({
  basePort: 8080,
  // Every container listens on 8080 internally and is reached by name.
  endpointFor: (_id, index) => `http://relay${index + 1}:8080/v1/relay`,
});

writeLocalMesh(out, mesh);
writeFileSync(
  join(out, 'README.txt'),
  'Generated by make-config.ts. Development only.\n' +
    'The .key files are real ML-KEM secret keys. Do not commit them and do not\n' +
    'point a wallet holding real value at this mesh.\n',
);

process.stdout.write(
  `wrote ${out}\n` +
    mesh.signed.directory.entries.map((e) => `  ${e.id} -> ${e.endpoint}\n`).join('') +
    `  keys: ${[...mesh.secretKeys.keys()].join(', ')} (0600, not printed)\n`,
);
